version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yaml

python:
  install:
    - requirements: dev/requirements_docs.txt
    - requirements: dev/requirements_all.txt
