name: Publish to PyPI

on:
  release:
    types: [published] # Trigger on a new GitHub release being published

jobs:
  build_and_publish:
    name: Build and Publish Python distribution to PyPI
    runs-on: ubuntu-latest # Run the job on an Ubuntu virtual machine
    # environment:
    #   name: pypi
    #   url: https://pypi.org/project/template-project/
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Action to checkout your repository code

      - name: Set up Python
        uses: actions/setup-python@v2 # Action to set up Python environment
        with:
          python-version: '3.12' # Use a recent Python version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build sdist and wheel
        run: python -m build

      # - name: Publish package distributions to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
        # with:
        #   repository-url: https://test.pypi.org/legacy/
